force-app/main/default/objects/Bank_Config__c/Bank_Config__c.object-meta.xml
<CustomObject>
    <label>Bank_Config</label>
    <nameField>
        <displayFormat>CONF-{0000}</displayFormat>
        <label>Bank_Config ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Config__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>BankName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Config__c/fields/BYNRate__c.field-meta.xml
<CustomField>
    <fullName>BYNRate__c</fullName>
    <label>BYNRate</label>
    <precision>16</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Config__c/fields/DepositPrc__c.field-meta.xml
<CustomField>
    <fullName>DepositPrc__c</fullName>
    <label>DepositPrc</label>
    <precision>13</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Config__c/fields/OtherBankPrc__c.field-meta.xml
<CustomField>
    <fullName>OtherBankPrc__c</fullName>
    <label>OtherBankPrc</label>
    <precision>13</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Config__c/fields/USDRate__c.field-meta.xml
<CustomField>
    <fullName>USDRate__c</fullName>
    <label>USDRate</label>
    <precision>16</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ATMController.cls
public with sharing class ATMController {
    @AuraEnabled
    public static Bank_Config__c getConfig() {
        
        // Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[] {
            'BankName__c', 'BYNRate__c', 'DepositPrc__c', 'OtherBankPrc__c', 'USDRate__c'
        };
        
        Map<String,Schema.SObjectField> fieldDescribeTokens = Schema.SObjectType.Bank_Config__c.fields.getMap();
        
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        
        List <Bank_Config__c>       configs;

        configs = [SELECT BankName__c, BYNRate__c, DepositPrc__c, OtherBankPrc__c, USDRate__c 
        FROM Bank_Config__c LIMIT 1];
        return configs[0];
    }
    /*
    @AuraEnabled
    public static Expense__c saveExpense(Expense__c expense) {
        // Perform isUpdateable() checking first, then
        upsert expense;
        return expense;
    }*/
}